#!/usr/bin/env sh

#
# Installs yzsh on home
#

set -eu

install -vm644 src/home/.yzsh-load.zsh ~/

if [ ! -d ~/.yzsh ]; then
  echo
  echo 'There is no ~/.yzsh data directory, copying from skel'

  cp -vr src/etc/skel/.yzsh ~/

  echo
  echo "Copied .yzsh data from skel. It's recomended to create a git repository of ~/.yzsh to save it"
fi

if [ ! -f ~/.yzsh.env ]; then
  ln -vs ~/.yzsh/yzsh.env ~/.yzsh.env
fi

if [ ! -f ~/.zshrc ] || ! grep -q '/.yzsh-load.zsh' ~/.zshrc; then
  cat <<'EOF' >>~/.zshrc

if [[ -f ~/.yzsh-load.zsh && -d ~/.yzsh ]]; then
  source ~/.yzsh-load.zsh && yzsh_main
fi
EOF

  echo
  echo 'Added yzsh loader to ~/.zshrc'
fi

echo
echo 'DONE'
